name: Deploy Flask App to EB

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.5"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          # Add your test commands here
          # python -m pytest tests/
          echo "Skipping tests for now"

      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x '*.git*' '*__pycache__*' '*.pyc' 'venv/*' '.env'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          application_name: test-flask-2
          environment_name: Test-flask-2-env
          version_label: ${{ github.sha }}
          region: us-east-2
          deployment_package: deploy.zip
